//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public string Sname { get; set; }
        public string Spassword { get; set; }
        public string Saddress { get; set; }
        public Nullable<int> Sage { get; set; }
        public Nullable<int> DepId { get; set; }
        public string email { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
